#!@path_perl@
######################################################################
##  !! ATTENTION: DO NOT EDIT THIS FILE, EVEN IF IT LOOKS LIKE  !!  ##
##  !! A STAND-ALONE PERL-SCRIPT. IT WAS AUTOMATICALLY COMPILED !!  ##
##  !! OUT OF MANY PERL SOURCE FILES. EDIT THOSE AND RECOMPILE. !!  ##
######################################################################

######################################
##                                  ##
##  nlp -- Postscript printer tool  ##
##                                  ##
######################################

require 5.000;

require "libAC.pl";
require "libSC.pl";
require "libMC.pl";
require "libVers.pl";
require "libGetopts.pl";
require "libTime.pl";
require "libFile.pl";
require "libTerm.pl";
require "libCap.pl";
require "libUtil.pl";

require "modInfo.pl";
require "modQueue.pl";
require "modNotify.pl";
require "modPrint.pl";
require "modMain.pl";

&Main::Main;

##EOF##
